{% set name = "alpha_vantage" %}
{% set version = "3.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f97fe2b8efad2da97580199d54f8556c8007053870c462d10b9eaa815186c484

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - aiohttp
    - python >={{ python_min }}
    - requests

test:
  imports:
    - alpha_vantage
    - alpha_vantage.async_support
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/RomelTorres/alpha_vantage
  summary: Python module to get stock data from the Alpha Vantage Api
  license: MIT
  license_file: LICENSE.txt
  doc_url: https://alpha-vantage.readthedocs.io/en/latest/
  dev_url: https://github.com/RomelTorres/alpha_vantage

extra:
  recipe-maintainers:
    - BastianZim
